dataset_params:
  root_dir: /mnt/bolin/Data/VoxCeleb/
  frame_shape: [256, 256, 3]
  id_sampling: True
  pairs_list: None
  augmentation_params:
    flip_param:
      horizontal_flip: True
      time_flip: True
    jitter_param:
      brightness: 0.1
      contrast: 0.1
      saturation: 0.1
      hue: 0.1


model_params:
  common_params:
    image_channel: 3                    
  generator_params:
    block_expansion: 64
    dense_motion_params:
      block_expansion: 32
      max_features: 1024
      num_blocks: 5
      num_channels: 3
      num_down_blocks: 2
      num_bottleneck_blocks: 2 
  discriminator_params:
    scales: [1] #####################
    block_expansion: 32                 
    max_features: 512
    num_blocks: 4
    sn: True

train_params:
  num_epochs: 1 #130
  num_repeats: 1 #30
  num_kp: 68 
  scale_factor: 0.25 
  epoch_milestones: [60,90]
  lr_generator: 2.0e-4
  lr_discriminator: 2.0e-4
  gan_mode: 'hinge'    # hinge or ls
  batch_size: 8  #24
  scales: [1, 0.5, 0.25, 0.125]
  checkpoint_freq: 10
  arcfacenet: './config/arcface_backbone_r50.pth'
  transform_params:
    sigma_affine: 0.05
    sigma_tps: 0.005
    points_tps: 5
  loss_weights:
    generator_gan_initial: 1  
    generator_gan: 1        
    discriminator_gan: 1 
    feature_matching: [10, 10, 10, 10]
    perceptual_initial: [10, 10, 10, 10, 10]    
    perceptual: [10, 10, 10, 10, 10]  
    face_features: [40, 40, 40, 40]     
    pixelrec: 100
    optical_flow: 20
    texture: [100, 100, 100, 100, 100] 
    
    
visualizer_params:
  kp_size: 2
  draw_border: True
  colormap: 'gist_rainbow'
